src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Annotations\GateKeeperProfile;
use App\Annotations\Semaphore;
use App\Entity\ActionCounter;
use App\Entity\Announcement;
use App\Entity\Citizen;
use App\Entity\CitizenProfession;
use App\Entity\CauseOfDeath;
use App\Entity\CitizenRole;
use App\Entity\CouncilEntry;
use App\Entity\HeroicActionPrototype;
use App\Entity\HeroSkillPrototype;
use App\Entity\ItemPrototype;
use App\Entity\LogEntryTemplate;
use App\Entity\Season;
use App\Entity\SpecialActionPrototype;
use App\Entity\TownLogEntry;
use App\Entity\User;
use App\Response\AjaxResponse;
use App\Service\CitizenHandler;
use App\Service\ConfMaster;
use App\Service\ErrorHelper;
use App\Service\GazetteService;
use App\Service\InventoryHandler;
use App\Service\ItemFactory;
use App\Service\JSONRequestParser;
use App\Service\LogTemplateHandler;
use App\Service\PictoHandler;
use App\Service\TimeKeeperService;
use App\Service\TownHandler;
use App\Service\UserHandler;
use App\Structures\ItemRequest;
use App\Structures\TownConf;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/",condition="request.isXmlHttpRequest()")
 * @GateKeeperProfile(only_incarnated=true)
 * @Semaphore("town", scope="town")
 * @method User getUser()
 */
class GameController extends CustomAbstractController
{
    private LogTemplateHandler $logTemplateHandler;
    private UserHandler $user_handler;
    private TownHandler $town_handler;
    private PictoHandler $picto_handler;
    private GazetteService $gazette_service;

    public function __construct(EntityManagerInterface $em, TranslatorInterface $translator, LogTemplateHandler $lth,
                                TimeKeeperService $tk, CitizenHandler $ch, UserHandler $uh, TownHandler $th,
                                ConfMaster $conf, PictoHandler $ph, InventoryHandler $ih, GazetteService $gs)
    {
        parent::__construct($conf, $em, $tk, $ch, $ih, $translator);
        $this->logTemplateHandler = $lth;
        $this->user_handler = $uh;
        $this->town_handler = $th;
        $this->picto_handler = $ph;
        $this->gazette_service = $gs;
    }

    protected function getActiveCitizen(): Citizen {
        return $this->entity_manager->getRepository(Citizen::class)->findActiveByUser($this->getUser());
    }

    protected function renderLog( ?int $day, $citizen = null, $zone = null, ?int $type = null, ?int $max = null ): Response {
        $entries = [];

        # Try to fetch one more log to check if we must display the "show more entries" message
        $nb_to_fetch = (is_null($max) or $max <= 0) ? $max : $max + 1;

        /** @var TownLogEntry $entity */
        foreach ($this->entity_manager->getRepository(TownLogEntry::class)->findByFilter(
            $this->getActiveCitizen()->getTown(),$day, $citizen, $zone, $type, $nb_to_fetch ) as $idx=>$entity) {

            /** @var LogEntryTemplate $template */
            $template = $entity->getLogEntryTemplate();
            if (!$template)
                continue;
            $entityVariables = $entity->getVariables();
            $entries[$idx] = [
                'timestamp' => $entity->getTimestamp(),
                'class'     => $template->getClass(),
                'type'      => $template->getType(),
                'id'        => $entity->getId(),
                'hidden'    => $entity->getHidden(),
            ];

            $variableTypes = $template->getVariableTypes();
            $transParams = $this->logTemplateHandler->parseTransParams($variableTypes, $entityVariables);

            try {
                $entries[$idx]['text'] = $this->translator->trans($template->getText(), $transParams, 'game');
            }
            catch (Exception $e) {
                $entries[$idx]['text'] = "null";
            }             
        }

        if ($day < 0) $day = $this->getActiveCitizen()->getTown()->getDay();

        $show_more_entries = false;
        if ($nb_to_fetch != $max) {
            $show_more_entries = count($entries) > $max;
            $entries = array_slice($entries, 0, $max);
        }

        $args = $this->addDefaultTwigArgs(null, [
                'day' => $day,
                'today' => $day === $this->getActiveCitizen()->getTown()->getDay(),
                'entries' => $entries,
                'show_more_entries' => $show_more_entries,
                'canHideEntry' => $this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getHeroic() && $this->user_handler->hasSkill($this->getUser(), 'manipulator') && $this->getActiveCitizen()->getSpecificActionCounterValue(ActionCounter::ActionTypeRemoveLog) < $this->user_handler->getMaximumEntryHidden($this->getUser()),
            ]
        );

        return $this->render( 'ajax/game/log_content.html.twig', $args);
    }

    /**
     * @Route("jx/game/landing", name="game_landing")
     * @return Response
     */
    public function landing(): Response
    {
        if (!$this->getActiveCitizen()->getAlive())
            return $this->redirect($this->generateUrl('soul_death'));
        elseif ($this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_jobs'));
        elseif (!$this->getActiveCitizen()->getHasSeenGazette())
            return $this->redirect($this->generateUrl('game_newspaper'));
        elseif ($this->getActiveCitizen()->getZone() && !$this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('beyond_dashboard'));
        elseif ($this->getActiveCitizen()->getZone() && $this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('exploration_dashboard'));
        else return $this->redirect($this->generateUrl('town_dashboard'));
    }

    /**
     * @Route("api/game/expert_toggle", name="game_toggle_expert_mode")
     * @param LogTemplateHandler $log
     * @return Response
     */
    public function toggle_expert_mode(LogTemplateHandler $log): Response
    {
        $this->entity_manager->persist( $this->getUser()->setExpert( !$this->getUser()->getExpert() ) );
        if ( !$this->getUser()->getExpert() && $this->getUser()->getActiveCitizen())
            foreach ($this->getUser()->getActiveCitizen()->getLeadingEscorts() as $escort) {
                $this->entity_manager->persist($log->beyondEscortReleaseCitizen($this->getUser()->getActiveCitizen(), $escort->getCitizen()));
                $escort->setLeader(null);
                $this->entity_manager->persist($escort);
            }
        try {
            $this->entity_manager->flush();
        } catch (Exception $e) { return AjaxResponse::error(ErrorHelper::ErrorDatabaseException); }
        return AjaxResponse::success();
    }

    /**
     * @Route("jx/game/raventimes", name="game_newspaper")
     * @return Response
     */
    public function newspaper(): Response {
        if ($this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_landing'));

        $in_town = $this->getActiveCitizen()->getZone() === null;
        $town = $this->getActiveCitizen()->getTown();

        $has_living_citizens = false;
        foreach ( $town->getCitizens() as $c )
            if ($c->getAlive()) {
                $has_living_citizens = true;
                break;
            }

        if (!$has_living_citizens && $this->getActiveCitizen()->getCauseOfDeath()->getRef() != CauseOfDeath::Radiations)
            return $this->redirect($this->generateUrl('game_landing'));

        $citizensWithRole = $this->entity_manager->getRepository(Citizen::class)->findCitizenWithRole($town);

        $roles = $this->entity_manager->getRepository(CitizenRole::class)->findVotable();

        $votesNeeded = array();
        foreach ($roles as $role)
            if ( $this->town_handler->is_vote_needed($town, $role) )
                $votesNeeded[$role->getName()] = $role;

        $show_register = $in_town || !$this->getActiveCitizen()->getAlive();

        $citizen = $this->getActiveCitizen();
        $citizen->setHasSeenGazette(true);
        $this->entity_manager->persist($citizen);
        $this->entity_manager->flush();

        $citizenRoleList = [];
        /** @var Citizen $citizen */
        foreach ($citizensWithRole as $citizen) {
            foreach ($citizen->getRoles() as $role) {
                if(isset($citizenRoleList[$role->getId()])) {
                    $citizenRoleList[$role->getId()]['citizens'][] = $citizen;
                } else {
                    $citizenRoleList[$role->getId()] = [
                        'role' => $role,
                        'citizens' => [
                            $citizen
                        ]
                    ];
                }
            }
        }

        $latest_announcement = $this->entity_manager->getRepository(Announcement::class)->findLatestByLang( $this->getUserLanguage() );

        return $this->render( 'ajax/game/newspaper.html.twig', $this->addDefaultTwigArgs(null, [
            'show_register'  => $show_register,
            'show_town_link'  => $in_town,
            'day' => $town->getDay(),
            'log' => $show_register ? $this->renderLog( -1, null, false, null, 50 )->getContent() : "",
            'gazette' => $this->gazette_service->renderGazette($town),
            'citizensWithRole' => $citizenRoleList,
            'votesNeeded' => $in_town ? $votesNeeded : [],
            'town' => $town,
            'announcement' => $latest_announcement?->getTimestamp() < new \DateTime('-4weeks') ? null : $latest_announcement,

templates/ajax/game/town/catapult.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Katapult'|trans({}, 'game')}}{% endblock %}
{% block content %}

    <h1 class="page-head">{{'Katapult'|trans({}, 'game')}}</h1>

    <div class="help">
        <strong>{{ 'Das Katapult ist ein wirklich mächtiges Instrument, um jeden beliebigen Gegenstand zu einer Zone in der Wüste zu schicken.'|trans({},'game') }}</strong>
        {{ 'Praktisch zur Versorgung aus der Ferne.'|trans({},'game') }}
        <p>{{ 'Denke daran, dass das Katapult manchmal sein Ziel verfehlt und den Gegenstand in eine angrenzende Zone befördert...'|trans({},'game')}}</p>
        <p>
            {% if is_catapult_master %}
                <strong>{{'Du wurdest als Verantwortlicher für das Katapult bestimmt!'|trans({},'game')}}</strong>
                {{'Wähle einen Gegenstand aus deinem Inventar und gib die Zielkoordinaten ein.'|trans({},'game')}}
            {% elseif catapult_master is not null %}
                {% macro playername(catapult_master) %}
                    {% include 'ajax/soul/playername.html.twig' with {user: catapult_master.user} only %}
                {% endmacro %}
                {{'Unser Katapult wird von dem vom Schicksal auserwählten Bürger {citizen} gesteuert. Sollte ihm etwas Schreckliches zustoßen, könnte dann ein neuer Bürger gewählt werden.'|trans({'{citizen}': _self.playername(catapult_master)},'game')|raw}}
            {% endif %}
        </p>
        {% if catapult_improved %}
            {{ 'Die Aktivierung des Katapults kostet {ap}.'|trans({'{ap}': '<div class="ap">2</div>'},'game')|raw }}
        {% else %}
            {{ 'Die Aktivierung des Katapults kostet {ap} (diese Kosten können durch den Bau eines besseren Katapults gesenkt werden).'|trans({'{ap}': '<div class="ap">4</div>'},'game')|raw }}
        {% endif %}
    </div>

    {% if catapult_master is null %}
        <p>
            <button id="cata_new">{{ 'Einen zufälligen Bürger als Katapult-Bediener auslosen'|trans({},'game') }}</button>
        </p>
    {% endif %}

    {% if is_catapult_master %}
        <div class="row">
            <div class="cell-small rw-10 ro-7 rw-md-14 ro-md-5 rw-sm-24 ro-sm-0">
                <div class="note">
                    <div class="center"><strong>{{ 'Zu verschickender Gegenstand:'|trans({},'game') }}</strong></div>
                    <div><label><select id="cata_what">
                        <option value="-1">-- {{ 'Gegenstand auswählen'|trans({},'game') }} --</option>
                        {% for item in app.user.activeCitizen.inventory.items %}
                            {# @var item \App\Entity\Item #}
                            {% if not item.essential and not item.broken %}
                                <option value="{{ item.id }}">{{ item.prototype.label|trans({},'items') }}</option>
                            {% endif %}
                        {% endfor %}
                    </select></label></div>
                    <div class="row">
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_x"><strong>X</strong></label></div>
                            <input id="cata_x" type="number" />
                        </div>
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_y"><strong>Y</strong></label></div>
                            <input id="cata_y" type="number" />
                        </div>
                    </div>
                    <div class="row"><div class="padded cell rw-12"><button id="cata_do">{{ 'Gegenstand katapultieren'|trans({},'game') }}</button></div></div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <h5>{% trans from 'game' %}Katapultregister{% endtrans %} <a class="float-right link" x-ajax-href="{{ path("game_newspaper") }}">{{ 'Das Gesamtregister ansehen'|trans({}, 'game') }}<div class="tooltip normal">{{ 'Dieser Link bringt dich zum <strong>Großen Register</strong>. Darin werden alle wichtigen Handlungen und Aktionen der Stadtbürger gespeichert...'|trans({}, 'game')|raw }}</div></a></h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_catapult_log_controller') } %}
            {% endembed %}
        </div>
    </div>

{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/log.js.twig" %}{% endembed %}

        {% if is_catapult_master %}
            $.html.addEventListenerAll('#cata_do', 'click', function () {
                const item = parseInt(document.getElementById('cata_what').value);
                const x = parseInt(document.getElementById('cata_x').value);
                const y = parseInt(document.getElementById('cata_y').value);

                if (item <= 0) {
                    $.html.message('error', '{{ 'Bitte wähle einen Gegenstand.'|trans({},'game') }}');
                    return;
                }
                if (isNaN(x) || isNaN(y)) {
                    $.html.message('error', '{{ 'Bitte gib die Zielkoordinaten ein.'|trans({},'game') }}');
                    return;
                }

                $.ajax.easySend( '{{ path('town_catapult_do_controller') }}', {item: item, x: x, y: y},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}

        {% if catapult_master is null %}
            $.html.addEventListenerAll('#cata_new', 'click', function () {
                $.ajax.easySend( '{{ path('town_catapult_assign_controller') }}', {},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/game/town/door.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Das Stadttor von "{townname}"'|trans({"{townname}": town.name}, 'game')|raw}}{% endblock %}
{% block tutorial %}
    <div x-tutorial-content="4.text3" class="toplevel text arrow-down">
        <div class="help">
            {% if town.door %}
                <p>{% trans from "help" %}
                        Das Stadttor ist geöffnet.
                    {% endtrans %}</p>
                <p>{% trans from "help" %}
                        Klick hier, um <strong>in die Wüste zu gehen</strong>... Sei jedoch vorsichtig!
                    {% endtrans %}</p>
                <button x-advance-tutorial="complete">{{ 'Weiter...'|trans({},'help') }}</button>
            {% else %}
                <p>{% trans from "help" %}
                        Du kannst <strong>das Stadttor</strong> in diesem Bereich öffnen... Achtung: Wenn das Tor beim allnächtlichen <strong>Angriff der Zombiehorde</strong> offen steht, kann das für die Stadt fatale Folgen haben...<strong></strong>
                    {% endtrans %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block content %}
    {% set hour = "now"|date("G") %}
    <div class="row">
        <div class="cell rw-12 town-banner town-banner-door-{% if town.door %}open{% else %}closed{% endif%} time-{{ hour }} {% if conf.isNightTime %}night{% endif %}"></div>
    </div>

    {% embed "ajax/game/town/door_tabs.html.twig" with {'door_section': door_section, 'has_battlement': has_battlement} %}
    {% endembed %}

    <div class="row-flex wrap town-summary">
        <div class="padded cell rw-4 ellipsis row-header"><img src="{{ asset('build/images/item/item_plate.gif') }}" alt="" /> {{'Stadtverteidigung'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 ellipsis row-detail">{{def}} <img src="{{ asset('build/images/icons/small_def.gif') }}" alt="" /> (<span class="link" x-ajax-href="{{ path('town_dashboard') }}">{{'Details ansehen'|trans({}, 'game')}}</span>)</div>
        <div class="padded cell rw-4 ellipsis row-header"><img src="{{ asset('build/images/item/item_door.gif') }}" alt="" /> {{'Lage'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 ellipsis row-detail">
            {% if town.door and town.devastated %}
                <span class="warning">{{'Stadttor zerstört!'|trans({}, 'game')}}</span>
            {% elseif (town.door) %}
                <span class="warning">{{'Stadttor geöffnet'|trans({}, 'game')}}</span>
            {% else %}
                {{'Stadttor geschlossen'|trans({}, 'game')}}
            {% endif %}
            <span class="small">(<span class="link" x-ajax-href="{{ path("town_citizens") }}">{{'Wer ist draußen?'|trans({}, 'game')}}</span>)</span>
        </div>
    </div>

    <div class="row">
        <div class="padded cell rw-6 rw-md-12">
            {% if not app.user.expert %}

                {% set has_packed_food = false %}
                {% set has_packed_water = false %}
                {% for item in app.user.activeCitizen.inventory.items %}
                    {% if item.prototype.hasProperty('is_water') %}{% set has_packed_water = true %}{% endif %}
                    {% if item.prototype.hasProperty('food') %}    {% set has_packed_food  = true %}{% endif %}
                {% endfor %}

                {% if not has_packed_food and not has_packed_water %}
                    <div x-conditional-help="door_equipment" class="no-arrow">
                        <p>{% trans from "help" %}
                                Es wäre vielleicht nicht verkehrt etwas <strong>Proviant</strong> (Nahrung und/oder Wasser) einzupacken, bevor du die Stadt verlässt... Gehe dazu in den Bereich <strong>Mein Zuhause</strong>.
                            {% endtrans %}</p>
                        <button x-confirm-conditional-help="door_equipment" x-temp="1">{{ 'Schließen'|trans({},'global') }}</button>
                    </div>
                {% endif %}
            {% endif %}

            {% if not can_go_out %}
                <div class="help">
                    <p>
                        {{'<strong>Du bist erschöpft</strong>, du kannst deshalb weder <strong>in die Außenwelt gehen</strong>, noch <strong>das Stadttor öffnen</strong>, noch <strong>es schließen</strong>.'|trans({}, 'game')|raw}}
                    </p>
                    <p>
                        {{'Trinke oder nimm einen Happen zu dir, aber unternimm etwas, um wieder in Schuss zu kommen!'|trans({}, 'game')}}
                    </p>
                </div>
            {% else %}
            {% if not town.devastated %}
                <div class="help">
                    {% trans from 'game' %}
                        Du kannst von hier aus die Stadt verlassen und die Außenwelt erkunden. Vergiss aber nicht, um Mitternacht das Tor zu schließen!
                    {% endtrans %}
                </div>

                {% if banished %}
                    <div class="note note-warning">
                        {% trans from 'game' %}
                            Du wurdest verbannt und kannst daher das Stadttor weder öffnen noch schließen.
                        {% endtrans %}
                    </div>
                {% endif %}
            {% else %}
                <div class="note note-critical">
                    {% trans from 'game' %}
                        Das Stadttor wurde bei einem besonders furchtbaren Angriff aus den Angeln gerissen und in die Aussenwelt geschleudert. Du solltest dich heute Nacht besser nicht hier aufhalten, sonst wird diese Stadt dein Grab.
                    {% endtrans %}
                    <br/><br/>
                    <strong>{% trans from 'game' %}
                        Das passiert eben, wenn man eine Stadt ohne einen einzigen Einwohner zurücklässt.
                    {% endtrans %}</strong>
                </div>
            {% endif %}
            <h5>{% trans from 'game' %}Meine Aktionen{% endtrans %}</h5>
                <div class="actions-box">
            {% if not banished %}
                {% if town.door %}
                    <div style="margin-bottom: 5px;">
                        <button id="door_closer" {% if town.devastated %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_action.gif') }}" />{% trans from 'game' %}Tor schließen{% endtrans %} (<div class="ap">1</div>)</button>
                        {% if town.devastated %}
                            <div class="tooltip">{{ 'Das Stadttor ist zerstört!'|trans({},'game') }}</div>
                        {% else %}
                            <div class="tooltip help">{{ 'Achtung! Alle Spieler, die sich außerhalb der Stadt befinden, können danach nicht mehr rein.'|trans({},'game') }}</div>
                        {% endif %}
                    </div>
                {% else %}
                    <button id="door_opener" {% if door_locked %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_action.gif') }}" />{% trans from 'game' %}Tor öffnen{% endtrans %} (<div class="ap">1</div>)</button>
                {% endif %}
            {% endif %}
            {% if show_ventilation %}
                <button id="door_exit_hero" {% if not allow_ventilation or not can_go_out %}disabled{% endif %}>
                    <img alt="" src="{{ asset('build/images/icons/star.gif') }}">{% trans from 'game' %}Durch die Lüftungsschächte klettern (out){% endtrans %}
                    <div class="tooltip help">{{ 'Diese Aktion wird durch ein Gebäude in der Stadt ermöglicht (nur Helden können sie verwenden).'|trans({},'game') }}</div>
                </button>
            {% endif %}
            {% if show_sneaky %}
                <button id="door_exit_sneak" {% if not town.door or not can_go_out %}disabled{% endif %}><img alt="" src="{{ asset('build/images/roles/ghoul.gif') }}">
                    {% trans from 'game' %}Aus der Stadt schleichen{% endtrans %}
                    <div class="tooltip help">{{ 'Mit dieser Aktion kannst du die Stadt verlassen, ohne dass es ins Stadtregister eingetragen wird.'|trans({},'game') }}</div>
                </button>
            {% endif %}
            <button id="door_exit" {% if not town.door or not can_go_out %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_move.gif') }}" />{% trans from 'game' %}Stadt verlassen{% endtrans %}</button>
            <button x-ajax-href="{{ path('town_routes') }}"><img alt="" src="{{ asset('build/images/item/item_bagxl.gif') }}" />{{ 'Route planen...'|trans({},'game') }}</button>
                </div>
            {% if town.door %}
                <div style="font-size: 1.2rem;">{{ 'Das Stadttor ist <span class="critical">geöffnet</span>! Achtung: Wenn das Tor geschlossen wird, können alle Spieler, die sich außerhalb der Stadt befinden, nicht mehr rein.'|trans({}, 'game')|raw }}</div>
            {% endif %}
            {% endif %}
        </div>
        <div class="padded cell rw-6 rw-md-12">
            <hordes-map id="door-map" data-react-mount="map" data-map="{{ map_public_json }}"></hordes-map>
            {{ help_lnk('Wie gebraucht man diese Karte?'|trans({},'game'), 'help', {'name': 'map'}) }}
        </div>
    </div>

    <p class="ambiant">
        {{'Das Stadttor ist Teil einer Festungsmauer, die den Großteil der Zombies abwehrt. Solltest du vergessen es am Abend zu schließen, kannst du dich auf Qualen einstellen, die deine schlimmsten Alpträume weit übertreffen.'|trans({}, 'game')}}
    </p>

    <div class="row">
        <h5>{{ 'Stadttor-Register'|trans({},'game') }} <a class="float-right link" x-ajax-href="{{ path("game_newspaper") }}">{{ 'Das Gesamtregister ansehen'|trans({}, 'game') }}<div class="tooltip normal">{{ 'Dieser Link bringt dich zum <strong>Großen Register</strong>. Darin werden alle wichtigen Handlungen und Aktionen der Stadtbürger gespeichert...'|trans({}, 'game')|raw }}</div></a></h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_door_log_controller') } %}
            {% endembed %}
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/log.js.twig" %}{% endembed %}

        const handleDoor = function(element, action) {
            if (!element) return;
            element.addEventListener('click', function() {
                if (!confirm('{{ 'Bestätigen?'|trans({},'global')|e('js') }}'))
                    return;
                $.ajax.easySend( '{{ path('town_door_control_controller') }}', {
                        action: action
                    },
                    function () {
                        $.ajax.load(null, '{{ path('town_door') }}', true);
                    } );
            });
        };

        {% if can_go_out %}
            handleDoor( document.getElementById('door_opener'), 'open' );
            handleDoor( document.getElementById('door_closer'), 'close' );

            document.getElementById('door_exit').addEventListener('click', function() {
                $.ajax.easySend( '{{ path('town_door_exit_controller') }}', {},
                    function () {
                        $.ajax.load(null, '{{ path('game_landing') }}', true);
                    } );
            });

            {% if show_ventilation and allow_ventilation %}
                document.getElementById('door_exit_hero').addEventListener('click', function() {
                    $.ajax.easySend( '{{ path('town_door_exit_controller', {'special': 'hero'}) }}', {},
                        function () {
                            $.ajax.load(null, '{{ path('game_landing') }}', true);
                        } );
                });
            {% endif %}
        {% endif %}

        {% if show_sneaky %}
            $.html.addEventListenerAll( '#door_exit_sneak', 'click', () => {
                if (!confirm('{{ 'Bestätigen?'|trans({},'global')|e('js') }}'))
                    return;
                $.ajax.easySend( '{{ path('town_door_exit_controller', {'special': 'sneak'}) }}', {},
                    function () {
                        $.ajax.load(null, '{{ path('game_landing') }}', true);
                    } );
            } );
        {% endif %}
    </script>
{% endblock %}

templates/ajax/game/town/door_tabs.html.twig
<ul class="tabs plain">
    <li class="tab {% if door_section == 'door' %}selected{% endif %}">
        <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_door') }}">{% trans from 'game' %}Stadttor{% endtrans %}</div>
    </li>
    <li class="tab {% if door_section == 'planner' %}selected{% endif %}">
        <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_routes') }}">{% trans from 'game' %}Expeditionen{% endtrans %}</div>
    </li>
    {% if has_battlement %}
        <li class="tab {% if door_section == 'nightwatch' %}selected{% endif %}">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_nightwatch') }}">{% trans from 'game' %}Nachtwache{% endtrans %}</div>
        </li>
    {% endif %}
</ul>